import type { MenuGroup, ResourceColumn, ResourceConfig, ResourceField, UserRole } from '../types';

const adminRoles: UserRole[] = ['admin', 'hr', 'manager'];
const text = (key: string, label: string, required = false): ResourceField => ({ key, label, kind: 'text', required });
const textarea = (key: string, label: string): ResourceField => ({ key, label, kind: 'textarea' });
const number = (key: string, label: string, required = false): ResourceField => ({ key, label, kind: 'number', required });
const date = (key: string, label: string): ResourceField => ({ key, label, kind: 'date' });
const datetime = (key: string, label: string): ResourceField => ({ key, label, kind: 'datetime' });
const multitag = (key: string, label: string): ResourceField => ({ key, label, kind: 'multitag' });
const json = (key: string, label: string): ResourceField => ({ key, label, kind: 'json' });
const select = (
  key: string,
  label: string,
  options: ResourceField['options'],
  required = false,
): ResourceField => ({
  key,
  label,
  kind: 'select',
  options,
  required,
});
const remoteSelect = (
  key: string,
  label: string,
  optionsEndpoint: string,
  optionLabelKey: string,
  required = false,
): ResourceField => ({
  key,
  label,
  kind: 'select',
  optionsEndpoint,
  optionLabelKey,
  optionValueKey: 'id',
  required,
});

const cols = (...columns: Array<[string, string, string | string[]]>): ResourceColumn[] =>
  columns.map(([key, title, dataIndex]) => ({ key, title, dataIndex, ellipsis: true }));

export const resourceGroups: MenuGroup[] = [
  {
    key: 'organization',
    label: '组织与员工',
    items: [
      {
        key: 'departments',
        label: '部门管理',
        group: 'organization',
        endpoint: 'departments',
        path: '/resources/departments',
        roles: adminRoles,
        fields: [
          remoteSelect('parentId', '上级部门', 'departments', 'name'),
          text('name', '部门名称', true),
          text('code', '部门编码', true),
          remoteSelect('managerEmployeeId', '负责人', 'employees', 'fullName'),
          textarea('description', '部门描述'),
        ],
        columns: cols(
          ['name', '部门名称', 'name'],
          ['code', '编码', 'code'],
          ['parent', '上级部门', ['parent', 'name']],
          ['description', '描述', 'description'],
        ),
      },
      {
        key: 'positions',
        label: '岗位管理',
        group: 'organization',
        endpoint: 'positions',
        path: '/resources/positions',
        roles: adminRoles,
        fields: [
          remoteSelect('departmentId', '所属部门', 'departments', 'name'),
          text('name', '岗位名称', true),
          text('code', '岗位编码', true),
          text('level', '职级', true),
          textarea('description', '岗位描述'),
        ],
        columns: cols(
          ['name', '岗位名称', 'name'],
          ['code', '编码', 'code'],
          ['department', '部门', ['department', 'name']],
          ['level', '职级', 'level'],
        ),
      },
      {
        key: 'employees',
        label: '员工档案',
        group: 'organization',
        endpoint: 'employees',
        path: '/resources/employees',
        roles: adminRoles,
        fields: [
          text('employeeNo', '工号', true),
          text('fullName', '姓名', true),
          text('email', '邮箱', true),
          text('phone', '手机号', true),
          select('gender', '性别', [
            { label: '男', value: 'male' },
            { label: '女', value: 'female' },
            { label: '未知', value: 'unknown' },
          ]),
          date('birthDate', '生日'),
          remoteSelect('departmentId', '部门', 'departments', 'name'),
          remoteSelect('positionId', '岗位', 'positions', 'name'),
          remoteSelect('managerEmployeeId', '直属经理', 'employees', 'fullName'),
          select('employmentType', '用工类型', [
            { label: '全职', value: 'full_time' },
            { label: '兼职', value: 'part_time' },
            { label: '实习', value: 'intern' },
          ]),
          select('employmentStatus', '状态', [
            { label: '试用', value: 'probation' },
            { label: '正式', value: 'active' },
            { label: '离职', value: 'exited' },
          ]),
          text('grade', '职级带宽'),
          date('joinDate', '入职日期'),
          date('probationEndDate', '试用期结束'),
          date('regularizationDate', '转正日期'),
          date('exitDate', '离职日期'),
          textarea('education', '学历背景'),
          multitag('certificates', '证书'),
          textarea('address', '地址'),
          json('emergencyContact', '紧急联系人信息'),
          text('nationalIdMasked', '身份证脱敏'),
          text('bankAccountMasked', '银行卡脱敏'),
          textarea('profileSummary', '简介'),
          text('avatarUrl', '头像地址'),
        ],
        columns: cols(
          ['employeeNo', '工号', 'employeeNo'],
          ['fullName', '姓名', 'fullName'],
          ['department', '部门', ['department', 'name']],
          ['position', '岗位', ['position', 'name']],
          ['employmentStatus', '状态', 'employmentStatus'],
        ),
      },
      {
        key: 'employee-contracts',
        label: '劳动合同',
        group: 'organization',
        endpoint: 'employee-contracts',
        path: '/resources/employee-contracts',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          text('contractNo', '合同编号', true),
          select('contractType', '合同类型', [
            { label: '劳动合同', value: 'labor' },
            { label: '劳务合同', value: 'service' },
          ], true),
          select('status', '合同状态', [
            { label: '生效', value: 'active' },
            { label: '过期', value: 'expired' },
          ], true),
          date('startDate', '开始日期'),
          date('endDate', '结束日期'),
          number('probationMonths', '试用月数'),
          number('salaryBase', '合同薪资'),
          { ...text('filePath', '文件路径'), downloadEndpoint: '/employee-contracts/:id/download' },
          textarea('notes', '备注'),
        ],
        columns: cols(
          ['contractNo', '合同编号', 'contractNo'],
          ['employee', '员工', ['employee', 'fullName']],
          ['contractType', '类型', 'contractType'],
          ['status', '状态', 'status'],
          ['startDate', '开始日期', 'startDate'],
        ),
      },
    ],
  },
  {
    key: 'recruitment',
    label: '招聘管理',
    items: [
      {
        key: 'job-postings',
        label: '职位发布',
        group: 'recruitment',
        endpoint: 'job-postings',
        path: '/resources/job-postings',
        roles: adminRoles,
        fields: [
          remoteSelect('departmentId', '部门', 'departments', 'name'),
          remoteSelect('positionId', '岗位', 'positions', 'name'),
          text('title', '职位名称', true),
          select('employmentType', '用工类型', [
            { label: '全职', value: 'full_time' },
            { label: '兼职', value: 'part_time' },
          ]),
          text('location', '工作地点'),
          textarea('description', '职位描述'),
          textarea('requirements', '岗位要求'),
          select('status', '状态', [
            { label: '草稿', value: 'draft' },
            { label: '招聘中', value: 'open' },
            { label: '关闭', value: 'closed' },
          ]),
          number('targetCount', '招聘人数'),
          datetime('publishedAt', '发布时间'),
          datetime('closedAt', '关闭时间'),
        ],
        columns: cols(
          ['title', '职位', 'title'],
          ['department', '部门', ['department', 'name']],
          ['location', '地点', 'location'],
          ['status', '状态', 'status'],
          ['targetCount', '人数', 'targetCount'],
        ),
      },
      {
        key: 'candidates',
        label: '候选人',
        group: 'recruitment',
        endpoint: 'candidates',
        path: '/resources/candidates',
        roles: adminRoles,
        fields: [
          remoteSelect('appliedJobPostingId', '应聘岗位', 'job-postings', 'title'),
          text('fullName', '姓名', true),
          text('email', '邮箱', true),
          text('phone', '手机号', true),
          select('source', '来源', [
            { label: '领英', value: 'linkedin' },
            { label: '内部推荐', value: 'referral' },
            { label: '校园招聘', value: 'campus' },
            { label: '社交媒体', value: 'social' },
          ]),
          select('stage', '阶段', [
            { label: '新入池', value: 'new' },
            { label: '筛选中', value: 'screening' },
            { label: '面试中', value: 'interview' },
            { label: '录用阶段', value: 'offer' },
            { label: '已录用', value: 'hired' },
            { label: '已淘汰', value: 'rejected' },
          ]),
          select('status', '状态', [
            { label: '进行中', value: 'active' },
            { label: '已录用', value: 'hired' },
            { label: '已淘汰', value: 'rejected' },
          ]),
          text('currentCompany', '现公司'),
          number('yearsOfExperience', '工作年限'),
          multitag('skills', '技能标签'),
          number('aiMatchScore', '智能匹配分'),
          textarea('notes', '备注'),
        ],
        columns: cols(
          ['fullName', '姓名', 'fullName'],
          ['appliedJobPosting', '岗位', ['appliedJobPosting', 'title']],
          ['stage', '阶段', 'stage'],
          ['status', '状态', 'status'],
          ['aiMatchScore', '匹配分', 'aiMatchScore'],
        ),
      },
      {
        key: 'resumes',
        label: '简历库',
        group: 'recruitment',
        endpoint: 'resumes',
        path: '/resources/resumes',
        roles: adminRoles,
        fields: [
          remoteSelect('candidateId', '候选人', 'candidates', 'fullName', true),
          text('fileName', '文件名', true),
          { ...text('filePath', '文件路径', true), downloadEndpoint: '/resumes/:id/download' },
          textarea('parsedText', '解析文本'),
          json('parsedProfile', '结构化档案信息'),
        ],
        columns: cols(
          ['fileName', '文件名', 'fileName'],
          ['candidate', '候选人', ['candidate', 'fullName']],
          ['uploadedAt', '上传时间', 'uploadedAt'],
          ['filePath', '路径', 'filePath'],
        ),
      },
      {
        key: 'interviews',
        label: '面试安排',
        group: 'recruitment',
        endpoint: 'interviews',
        path: '/resources/interviews',
        roles: adminRoles,
        fields: [
          remoteSelect('candidateId', '候选人', 'candidates', 'fullName', true),
          remoteSelect('jobPostingId', '职位', 'job-postings', 'title'),
          remoteSelect('interviewerEmployeeId', '面试官', 'employees', 'fullName'),
          datetime('scheduledAt', '面试时间'),
          select('interviewType', '面试方式', [
            { label: '现场', value: 'onsite' },
            { label: '视频', value: 'video' },
          ]),
          select('status', '状态', [
            { label: '待面试', value: 'scheduled' },
            { label: '完成', value: 'completed' },
            { label: '取消', value: 'cancelled' },
          ]),
          number('score', '评分'),
          textarea('feedback', '反馈'),
        ],
        columns: cols(
          ['candidate', '候选人', ['candidate', 'fullName']],
          ['jobPosting', '职位', ['jobPosting', 'title']],
          ['scheduledAt', '时间', 'scheduledAt'],
          ['status', '状态', 'status'],
          ['score', '评分', 'score'],
        ),
      },
      {
        key: 'offers',
        label: '录用管理',
        group: 'recruitment',
        endpoint: 'offers',
        path: '/resources/offers',
        roles: adminRoles,
        fields: [
          remoteSelect('candidateId', '候选人', 'candidates', 'fullName', true),
          remoteSelect('jobPostingId', '职位', 'job-postings', 'title'),
          remoteSelect('approvalByEmployeeId', '审批人', 'employees', 'fullName'),
          number('salaryOffered', '录用薪资'),
          select('status', '状态', [
            { label: '草稿', value: 'draft' },
            { label: '已发出', value: 'sent' },
            { label: '已接受', value: 'accepted' },
            { label: '已拒绝', value: 'rejected' },
          ]),
          datetime('offeredAt', '发放时间'),
          datetime('acceptedAt', '接受时间'),
          textarea('notes', '备注'),
        ],
        columns: cols(
          ['candidate', '候选人', ['candidate', 'fullName']],
          ['jobPosting', '职位', ['jobPosting', 'title']],
          ['salaryOffered', '薪资', 'salaryOffered'],
          ['status', '状态', 'status'],
          ['offeredAt', '发放时间', 'offeredAt'],
        ),
      },
    ],
  },
  {
    key: 'attendance',
    label: '考勤休假',
    items: [
      {
        key: 'attendances',
        label: '考勤记录',
        group: 'attendance',
        endpoint: 'attendances',
        path: '/resources/attendances',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          date('workDate', '日期'),
          datetime('clockInAt', '上班打卡'),
          datetime('clockOutAt', '下班打卡'),
          select('status', '状态', [
            { label: '正常', value: 'present' },
            { label: '迟到', value: 'late' },
            { label: '异常', value: 'anomaly' },
          ]),
          select('source', '来源', [
            { label: '网页端', value: 'web' },
            { label: '移动端', value: 'mobile' },
          ]),
          number('lateMinutes', '迟到分钟'),
          number('undertimeMinutes', '早退分钟'),
          textarea('anomalyReason', '异常原因'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['workDate', '日期', 'workDate'],
          ['status', '状态', 'status'],
          ['lateMinutes', '迟到', 'lateMinutes'],
          ['undertimeMinutes', '早退', 'undertimeMinutes'],
        ),
      },
      {
        key: 'leave-requests',
        label: '请假申请',
        group: 'attendance',
        endpoint: 'leave-requests',
        path: '/resources/leave-requests',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          remoteSelect('approverEmployeeId', '审批人', 'employees', 'fullName'),
          select('leaveType', '假期类型', [
            { label: '年假', value: 'annual' },
            { label: '病假', value: 'sick' },
            { label: '婚假', value: 'marriage' },
            { label: '事假', value: 'personal' },
            { label: '产假', value: 'maternity' },
            { label: '陪产假', value: 'paternity' },
          ], true),
          datetime('startAt', '开始时间'),
          datetime('endAt', '结束时间'),
          number('durationDays', '天数'),
          textarea('reason', '原因'),
          select('status', '状态', [
            { label: '待审批', value: 'pending' },
            { label: '已通过', value: 'approved' },
            { label: '已驳回', value: 'rejected' },
          ]),
          textarea('rejectionReason', '驳回原因'),
          datetime('approvedAt', '审批时间'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['leaveType', '类型', 'leaveType'],
          ['startAt', '开始', 'startAt'],
          ['endAt', '结束', 'endAt'],
          ['status', '状态', 'status'],
        ),
      },
      {
        key: 'leave-balances',
        label: '假期余额',
        group: 'attendance',
        endpoint: 'leave-balances',
        path: '/resources/leave-balances',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          select('leaveType', '假期类型', [
            { label: '年假', value: 'annual' },
            { label: '病假', value: 'sick' },
            { label: '婚假', value: 'marriage' },
            { label: '事假', value: 'personal' },
            { label: '产假', value: 'maternity' },
            { label: '陪产假', value: 'paternity' },
          ], true),
          number('year', '年度', true),
          number('totalDays', '总天数', true),
          number('usedDays', '已用'),
          number('remainingDays', '剩余'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['leaveType', '类型', 'leaveType'],
          ['year', '年度', 'year'],
          ['totalDays', '总天数', 'totalDays'],
          ['remainingDays', '剩余', 'remainingDays'],
        ),
      },
      {
        key: 'overtime-requests',
        label: '加班申请',
        group: 'attendance',
        endpoint: 'overtime-requests',
        path: '/resources/overtime-requests',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          remoteSelect('approverEmployeeId', '审批人', 'employees', 'fullName'),
          date('workDate', '加班日期'),
          datetime('startAt', '开始时间'),
          datetime('endAt', '结束时间'),
          number('hours', '小时数'),
          textarea('reason', '原因'),
          select('status', '状态', [
            { label: '待审批', value: 'pending' },
            { label: '已通过', value: 'approved' },
            { label: '已驳回', value: 'rejected' },
          ]),
          datetime('approvedAt', '审批时间'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['workDate', '日期', 'workDate'],
          ['hours', '时长', 'hours'],
          ['status', '状态', 'status'],
          ['approvedAt', '审批时间', 'approvedAt'],
        ),
      },
    ],
  },
  {
    key: 'performance',
    label: '绩效管理',
    items: [
      {
        key: 'performance-cycles',
        label: '考核周期',
        group: 'performance',
        endpoint: 'performance-cycles',
        path: '/resources/performance-cycles',
        roles: adminRoles,
        fields: [
          text('name', '周期名称', true),
          number('year', '年度', true),
          select('periodType', '周期类型', [
            { label: '季度', value: 'quarterly' },
            { label: '月度', value: 'monthly' },
          ]),
          date('startDate', '开始日期'),
          date('endDate', '结束日期'),
          select('status', '状态', [
            { label: '草稿', value: 'draft' },
            { label: '进行中', value: 'active' },
            { label: '已结束', value: 'closed' },
          ]),
        ],
        columns: cols(
          ['name', '名称', 'name'],
          ['year', '年度', 'year'],
          ['periodType', '类型', 'periodType'],
          ['startDate', '开始', 'startDate'],
          ['status', '状态', 'status'],
        ),
      },
      {
        key: 'performance-goals',
        label: '绩效目标',
        group: 'performance',
        endpoint: 'performance-goals',
        path: '/resources/performance-goals',
        roles: adminRoles,
        fields: [
          remoteSelect('cycleId', '周期', 'performance-cycles', 'name', true),
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          text('title', '目标', true),
          select('category', '类型', [
            { label: '目标与关键结果', value: 'okr' },
            { label: '关键绩效指标', value: 'kpi' },
          ]),
          number('weight', '权重'),
          text('targetValue', '目标值'),
          text('currentValue', '当前值'),
          select('status', '状态', [
            { label: '进行中', value: 'in_progress' },
            { label: '已完成', value: 'completed' },
          ]),
          textarea('description', '说明'),
        ],
        columns: cols(
          ['title', '目标', 'title'],
          ['employee', '员工', ['employee', 'fullName']],
          ['cycle', '周期', ['cycle', 'name']],
          ['weight', '权重', 'weight'],
          ['status', '状态', 'status'],
        ),
      },
      {
        key: 'performance-reviews',
        label: '绩效评审',
        group: 'performance',
        endpoint: 'performance-reviews',
        path: '/resources/performance-reviews',
        roles: adminRoles,
        fields: [
          remoteSelect('cycleId', '周期', 'performance-cycles', 'name', true),
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          remoteSelect('reviewerEmployeeId', '评审人', 'employees', 'fullName'),
          number('overallScore', '总分'),
          select('rating', '评级', [
            { label: '符合预期', value: 'meets_expectation' },
            { label: '超出预期', value: 'exceeds_expectation' },
          ]),
          textarea('strengths', '优势'),
          textarea('improvements', '改进项'),
          textarea('summary', '总结'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['cycle', '周期', ['cycle', 'name']],
          ['overallScore', '总分', 'overallScore'],
          ['rating', '评级', 'rating'],
          ['summary', '总结', 'summary'],
        ),
      },
    ],
  },
  {
    key: 'payroll',
    label: '薪酬管理',
    items: [
      {
        key: 'salary-configs',
        label: '薪资结构',
        group: 'payroll',
        endpoint: 'salary-configs',
        path: '/resources/salary-configs',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          select('payType', '发薪方式', [
            { label: '月薪制', value: 'monthly' },
          ]),
          number('baseSalary', '基本工资', true),
          number('housingAllowance', '住房补贴'),
          number('transportAllowance', '交通补贴'),
          number('bonusRate', '奖金系数'),
          number('socialInsuranceBase', '社保基数'),
          number('taxRate', '税率'),
          date('effectiveFrom', '生效日期'),
          date('effectiveTo', '失效日期'),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['baseSalary', '基本工资', 'baseSalary'],
          ['housingAllowance', '住房补贴', 'housingAllowance'],
          ['taxRate', '税率', 'taxRate'],
          ['effectiveFrom', '生效', 'effectiveFrom'],
        ),
      },
      {
        key: 'salary-records',
        label: '工资记录',
        group: 'payroll',
        endpoint: 'salary-records',
        path: '/resources/salary-records',
        roles: adminRoles,
        fields: [
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          date('month', '月份'),
          number('attendanceDays', '出勤天数'),
          number('overtimeHours', '加班小时'),
          number('performanceScore', '绩效分'),
          number('grossPay', '应发工资'),
          number('deductions', '扣款'),
          number('netPay', '实发工资'),
          select('status', '状态', [
            { label: '已生成', value: 'generated' },
            { label: '已发布', value: 'published' },
          ]),
        ],
        columns: cols(
          ['employee', '员工', ['employee', 'fullName']],
          ['month', '月份', 'month'],
          ['grossPay', '应发', 'grossPay'],
          ['netPay', '实发', 'netPay'],
          ['status', '状态', 'status'],
        ),
      },
      {
        key: 'payslips',
        label: '工资单',
        group: 'payroll',
        endpoint: 'payslips',
        path: '/resources/payslips',
        roles: adminRoles,
        fields: [
          remoteSelect('salaryRecordId', '工资记录', 'salary-records', 'month', true),
          remoteSelect('employeeId', '员工', 'employees', 'fullName', true),
          text('slipNo', '工资单号', true),
          datetime('issuedAt', '签发时间'),
          { ...text('downloadPath', '下载路径'), downloadEndpoint: '/payslips/:id/download' },
          { key: 'visibleToEmployee', label: '员工可见', kind: 'switch' },
        ],
        columns: cols(
          ['slipNo', '工资单号', 'slipNo'],
          ['employee', '员工', ['employee', 'fullName']],
          ['issuedAt', '签发时间', 'issuedAt'],
          ['downloadPath', '文件', 'downloadPath'],
          ['visibleToEmployee', '可见', 'visibleToEmployee'],
        ),
      },
    ],
  },
];

export const resourceMap = Object.fromEntries(resourceGroups.flatMap((group) => group.items.map((item) => [item.key, item])));
